repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^django_simple_bulma/(css|bulma|extensions)/
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: ^django_simple_bulma/(css|bulma|extensions)/

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/crate-ci/typos
    rev: v1.28.4
    hooks:
      - id: typos
        exclude: ^django_simple_bulma/(bulma|extensions|css)/
